name: Deploy ke GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_QRIS_API_URL: ${{ secrets.VITE_QRIS_API_URL }}
          VITE_QRIS_STRING: ${{ secrets.VITE_QRIS_STRING }}
          VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}

      - name: Deploy ke GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
